pip install numpy==1.26.4
pip install torch==2.2.2
pip install torchvision==0.17.2
pip install xformers==0.0.25.post1
pip install datasets
pip install accelerate
pip install timm
pip install transformers
pip install torchmetrics
pip install torch_fidelity
pip install diffusers
pip install torchdiffeq
pip install einops
pip install deepspeed
pip install wandb
pip install flash-attn
pip install omegaconf
pip install matplotlib
pip install beartype
pip install kornia 
pip install PyAV
pip install moviepy 
pip install imageio